import { z } from 'zod';

/**
 * Parsing of Resend's `email.received` webhook and of inbound email itself:
 * pulling the account out of the recipient address, the sender out of the
 * `From`, the customer's words out of a reply full of quoted history — and
 * recognizing the auto-responder mail the agent must never answer (or two
 * out-of-office bots will happily schedule each other forever).
 */

/**
 * The webhook body for an inbound email. Resend's `email.received` event
 * carries metadata only — the body text is fetched separately by id. The
 * optional `text`/`html`/`headers` fields are read when present (they also
 * make local testing with `curl` easy) so a payload that does include content
 * needs no second round-trip.
 */
export const inboundEmailEventSchema = z.object({
	type: z.string(),
	data: z.object({
		email_id: z.string().default(''),
		from: z.string().default(''),
		to: z.array(z.string()).default([]),
		cc: z.array(z.string()).default([]),
		/** Original recipients when the mail was forwarded into Resend. */
		received_for: z.array(z.string()).default([]),
		message_id: z.string().default(''),
		subject: z.string().default(''),
		text: z.string().optional(),
		html: z.string().optional(),
		headers: z.record(z.string(), z.string()).optional(),
	}),
});
export type InboundEmailEvent = z.infer<typeof inboundEmailEventSchema>;

/** The one event type this channel handles. */
export const INBOUND_EMAIL_EVENT = 'email.received';

/** A parsed `From`/`To` mailbox: display name (may be '') + bare address. */
export interface ParsedAddress {
	name: string;
	address: string;
}

/**
 * Read an RFC 5322-ish mailbox — `Dana Fox <dana@example.com>`, `"Fox, Dana"
 * <dana@example.com>`, or a bare `dana@example.com` — into name + address.
 * Returns null when no plausible address is present.
 */
export function parseAddress(raw: string): ParsedAddress | null {
	const trimmed = raw.trim();
	const angled = trimmed.match(/^(.*?)<([^<>\s]+@[^<>\s]+)>\s*$/);
	if (angled?.[2]) {
		const name = (angled[1] ?? '')
			.trim()
			.replace(/^"(.*)"$/, '$1')
			.trim();
		return { name, address: angled[2].toLowerCase() };
	}
	if (/^[^<>\s]+@[^<>\s]+\.[^<>\s]+$/.test(trimmed)) {
		return { name: '', address: trimmed.toLowerCase() };
	}
	return null;
}

/**
 * The agent address this email was sent to: the first recipient (To, then Cc,
 * then forwarded-for) at the agent domain. Returns its local part — the
 * account's slug or id — or null when the mail wasn't addressed to the agent
 * domain at all.
 */
export function resolveAgentRecipient(
	event: InboundEmailEvent,
	agentDomain: string,
): string | null {
	const suffix = `@${agentDomain.toLowerCase()}`;
	const recipients = [...event.data.to, ...event.data.cc, ...event.data.received_for];
	for (const raw of recipients) {
		const parsed = parseAddress(raw);
		if (parsed?.address.endsWith(suffix)) {
			const localPart = parsed.address.slice(0, -suffix.length);
			if (localPart !== '') {
				return localPart;
			}
		}
	}
	return null;
}

// Header values that mark machine-generated mail (RFC 3834 and the de-facto
// Microsoft/Precedence conventions).
const AUTO_SUBMITTED = 'auto-submitted';
const AUTO_RESPONSE_SUPPRESS = 'x-auto-response-suppress';
const PRECEDENCE = 'precedence';
const AUTO_PRECEDENCE = new Set(['bulk', 'junk', 'list', 'auto_reply']);

/**
 * Whether an inbound email is one the agent must not answer: something the
 * agent domain itself sent (a forwarding loop) or an auto-generated message
 * (out-of-office, delivery report). Answering either would start a mail loop.
 */
export function isAutoGenerated(input: {
	fromAddress: string;
	agentDomain: string;
	headers: Record<string, string>;
}): boolean {
	if (input.fromAddress.endsWith(`@${input.agentDomain.toLowerCase()}`)) {
		return true;
	}
	const headers = new Map(
		Object.entries(input.headers).map(([key, value]) => [key.toLowerCase(), value.toLowerCase()]),
	);
	const autoSubmitted = headers.get(AUTO_SUBMITTED);
	if (autoSubmitted && autoSubmitted !== 'no') {
		return true;
	}
	if (headers.has(AUTO_RESPONSE_SUPPRESS)) {
		return true;
	}
	const precedence = headers.get(PRECEDENCE);
	if (precedence && AUTO_PRECEDENCE.has(precedence)) {
		return true;
	}
	return false;
}

// Where a reply's fresh text ends and quoted history begins. Matched per line.
const QUOTE_MARKERS = [
	/^\s*on .{0,200} wrote:\s*$/i, // "On Jul 1, 2026, at 9:12 AM, Rivus wrote:"
	/^\s*-{2,}\s*original message\s*-{2,}\s*$/i,
	/^\s*-{2,}\s*forwarded message\s*-{2,}\s*$/i,
	/^\s*from:\s.*$/i, // Outlook-style quoted header block
	/^\s*_{10,}\s*$/, // Outlook divider
];

/**
 * The sender's own words: everything above the first quoted-history marker,
 * with `>`-quoted lines dropped and whitespace tidied. Deliberately
 * conservative — when no marker is recognized the whole text is kept, since
 * losing fresh words is worse than reading a stale line.
 */
export function extractReplyText(text: string): string {
	const kept: string[] = [];
	for (const line of text.split(/\r?\n/)) {
		if (QUOTE_MARKERS.some((marker) => marker.test(line))) {
			break;
		}
		if (/^\s*>/.test(line)) {
			continue;
		}
		kept.push(line);
	}
	return kept.join('\n').trim();
}

/**
 * A crude but dependency-free fallback when an email has HTML and no text
 * part. The output is plain text handed to the reply parser and transcript —
 * it is never rendered as HTML, so this is a readability aid, not a sanitizer.
 */
export function htmlToText(html: string): string {
	return (
		html
			// `\s*>` also matches sloppy closers like `</script >`.
			.replace(/<(?:style|script)[\s\S]*?<\/(?:style|script)\s*>/gi, ' ')
			.replace(/<br\s*\/?>/gi, '\n')
			.replace(/<\/(?:p|div|li|tr|h[1-6])>/gi, '\n')
			.replace(/<[^>]+>/g, ' ')
			.replace(/&nbsp;/gi, ' ')
			.replace(/&lt;/gi, '<')
			.replace(/&gt;/gi, '>')
			.replace(/&quot;/gi, '"')
			.replace(/&#39;/gi, "'")
			// `&amp;` is decoded last so `&amp;lt;` yields the literal text "&lt;"
			// the author wrote, rather than being double-unescaped into "<".
			.replace(/&amp;/gi, '&')
			.replace(/[ \t]+/g, ' ')
			.split('\n')
			.map((line) => line.trim())
			.join('\n')
			.replace(/\n{3,}/g, '\n\n')
			.trim()
	);
}

/** Strip `Re:`/`Fwd:` chains off a subject; '' stays ''. */
export function cleanSubject(subject: string): string {
	let cleaned = subject.trim();
	const prefix = /^(?:re|fwd?|fw)\s*:\s*/i;
	while (prefix.test(cleaned)) {
		cleaned = cleaned.replace(prefix, '');
	}
	return cleaned.trim();
}
