import { describe, expect, it, vi } from 'vitest';
import {
	agentAddressLocalPart,
	cleanSubject,
	extractReplyText,
	htmlToText,
	inboundEmailEventSchema,
	isAutoGenerated,
	parseAddress,
	resolveAgentRecipient,
} from '../src/services/agent/email/inbound';
import {
	createReceivedEmailReader,
	NoopReceivedEmailReader,
	ResendReceivedEmailReader,
} from '../src/services/agent/email/received';
import {
	type AgentEmailRenderContext,
	renderAgentEmail,
	renderAgentReplyText,
	replySubject,
} from '../src/services/agent/email/templates';
import {
	signWebhookPayload,
	verifyWebhookSignature,
	WEBHOOK_TOLERANCE_SECONDS,
} from '../src/services/agent/email/webhook';
import type { AgentDecision } from '../src/services/agent/engine';
import { buildCustomerSignupUrl } from '../src/services/agent/signup';
import type { FetchLike } from '../src/services/resend-mailer';
import { ResendMailer } from '../src/services/resend-mailer';

const SECRET = `whsec_${Buffer.from('test-signing-key').toString('base64')}`;
const NOW = new Date('2026-07-01T17:00:00.000Z');

function signedHeaders(payload: string, overrides: Partial<Record<string, string>> = {}) {
	const id = overrides.id ?? 'msg_1';
	const timestamp = overrides.timestamp ?? String(Math.floor(NOW.getTime() / 1000));
	const signature =
		overrides.signature ?? signWebhookPayload({ secret: SECRET, id, timestamp, payload });
	return { id, timestamp, signature };
}

describe('verifyWebhookSignature', () => {
	const payload = '{"type":"email.received"}';

	it('accepts a correctly signed, fresh payload', () => {
		expect(
			verifyWebhookSignature({
				secret: SECRET,
				headers: signedHeaders(payload),
				payload,
				now: NOW,
			}),
		).toBe(true);
	});

	it('accepts a rotated-secret header carrying multiple signatures', () => {
		const headers = signedHeaders(payload);
		headers.signature = `v1,${Buffer.from('wrong').toString('base64')} ${headers.signature}`;
		expect(verifyWebhookSignature({ secret: SECRET, headers, payload, now: NOW })).toBe(true);
	});

	it('rejects a tampered payload', () => {
		expect(
			verifyWebhookSignature({
				secret: SECRET,
				headers: signedHeaders(payload),
				payload: '{"type":"email.received","evil":true}',
				now: NOW,
			}),
		).toBe(false);
	});

	it('rejects the wrong secret', () => {
		expect(
			verifyWebhookSignature({
				secret: `whsec_${Buffer.from('other-key').toString('base64')}`,
				headers: signedHeaders(payload),
				payload,
				now: NOW,
			}),
		).toBe(false);
	});

	it('rejects a stale timestamp (replay guard)', () => {
		const staleSeconds = Math.floor(NOW.getTime() / 1000) - WEBHOOK_TOLERANCE_SECONDS - 1;
		const headers = signedHeaders(payload, { timestamp: String(staleSeconds) });
		expect(verifyWebhookSignature({ secret: SECRET, headers, payload, now: NOW })).toBe(false);
	});

	it('rejects missing or malformed headers', () => {
		expect(
			verifyWebhookSignature({
				secret: SECRET,
				headers: { id: '', timestamp: '', signature: '' },
				payload,
				now: NOW,
			}),
		).toBe(false);
		const headers = signedHeaders(payload, { timestamp: 'not-a-number' });
		expect(verifyWebhookSignature({ secret: SECRET, headers, payload, now: NOW })).toBe(false);
		expect(
			verifyWebhookSignature({
				secret: SECRET,
				headers: { ...signedHeaders(payload), signature: 'v2,abc' },
				payload,
				now: NOW,
			}),
		).toBe(false);
	});
});

describe('parseAddress', () => {
	it('parses name-addr, quoted name-addr, and bare addresses', () => {
		expect(parseAddress('Dana Fox <Dana@Example.com>')).toEqual({
			name: 'Dana Fox',
			address: 'dana@example.com',
		});
		expect(parseAddress('"Fox, Dana" <dana@example.com>')).toEqual({
			name: 'Fox, Dana',
			address: 'dana@example.com',
		});
		expect(parseAddress('  dana@example.com ')).toEqual({ name: '', address: 'dana@example.com' });
	});

	it('returns null for garbage', () => {
		expect(parseAddress('not an address')).toBeNull();
		expect(parseAddress('')).toBeNull();
	});
});

describe('resolveAgentRecipient', () => {
	function event(to: string[], cc: string[] = [], receivedFor: string[] = []) {
		return inboundEmailEventSchema.parse({
			type: 'email.received',
			data: { to, cc, received_for: receivedFor, from: 'x@y.zz' },
		});
	}

	it('finds the agent-domain recipient and returns its local part', () => {
		expect(resolveAgentRecipient(event(['cascade-plumbing@riv.us']), 'riv.us')).toBe(
			'cascade-plumbing',
		);
	});

	it('looks through To, then Cc, then received_for', () => {
		expect(resolveAgentRecipient(event(['other@example.com'], ['acme@riv.us']), 'riv.us')).toBe(
			'acme',
		);
		expect(
			resolveAgentRecipient(event(['other@example.com'], [], ['Acme <acme@riv.us>']), 'riv.us'),
		).toBe('acme');
	});

	it('is case-insensitive about the domain and address', () => {
		expect(resolveAgentRecipient(event(['Acme@RIV.US']), 'riv.us')).toBe('acme');
	});

	it('returns null when no recipient is at the agent domain', () => {
		expect(resolveAgentRecipient(event(['someone@example.com']), 'riv.us')).toBeNull();
		expect(resolveAgentRecipient(event([]), 'riv.us')).toBeNull();
	});

	it('throws away the other environment’s domain alias (keeps dev/prod isolated)', () => {
		// Production runs AGENT_EMAIL_DOMAIN=riv.us and must ignore mail to the
		// development alias — the `@`-anchored match means `@dev.riv.us` is not a
		// match for `@riv.us`, even though `dev.riv.us` is a subdomain of `riv.us`.
		expect(resolveAgentRecipient(event(['cascade-1a2b3c4d@dev.riv.us']), 'riv.us')).toBeNull();
		// Development runs AGENT_EMAIL_DOMAIN=dev.riv.us: it serves its own subdomain
		// and rejects the bare production domain.
		expect(resolveAgentRecipient(event(['cascade-1a2b3c4d@dev.riv.us']), 'dev.riv.us')).toBe(
			'cascade-1a2b3c4d',
		);
		expect(resolveAgentRecipient(event(['cascade-1a2b3c4d@riv.us']), 'dev.riv.us')).toBeNull();
	});
});

describe('agentAddressLocalPart', () => {
	it('returns the local part of one of our agent addresses (case-insensitive)', () => {
		expect(agentAddressLocalPart('Cascade-Plumbing@RIV.US', 'riv.us')).toBe('cascade-plumbing');
	});

	it('returns null for an address at another domain, or with an empty local part', () => {
		expect(agentAddressLocalPart('hello@rivus.ai', 'riv.us')).toBeNull();
		expect(agentAddressLocalPart('@riv.us', 'riv.us')).toBeNull();
	});

	it('does not treat the other environment’s domain alias as ours', () => {
		// The bounce/complaint path identifies the account from our own From address;
		// a prod deployment must not read a `dev.riv.us` sender as one of its agent
		// addresses (nor the reverse), so the two inboxes never cross over.
		expect(agentAddressLocalPart('acme-1a2b3c4d@dev.riv.us', 'riv.us')).toBeNull();
		expect(agentAddressLocalPart('acme-1a2b3c4d@dev.riv.us', 'dev.riv.us')).toBe('acme-1a2b3c4d');
		expect(agentAddressLocalPart('acme-1a2b3c4d@riv.us', 'dev.riv.us')).toBeNull();
	});
});

describe('isAutoGenerated', () => {
	const base = { fromAddress: 'dana@example.com', agentDomain: 'riv.us' };

	it('flags mail from the agent domain itself (loop guard)', () => {
		expect(isAutoGenerated({ ...base, fromAddress: 'acme@riv.us', headers: {} })).toBe(true);
	});

	it('flags RFC 3834 auto-submitted mail, but not auto-submitted: no', () => {
		expect(isAutoGenerated({ ...base, headers: { 'Auto-Submitted': 'auto-replied' } })).toBe(true);
		expect(isAutoGenerated({ ...base, headers: { 'auto-submitted': 'no' } })).toBe(false);
	});

	it('flags X-Auto-Response-Suppress and bulk precedence', () => {
		expect(isAutoGenerated({ ...base, headers: { 'X-Auto-Response-Suppress': 'All' } })).toBe(true);
		expect(isAutoGenerated({ ...base, headers: { Precedence: 'bulk' } })).toBe(true);
		expect(isAutoGenerated({ ...base, headers: { precedence: 'first-class' } })).toBe(false);
	});

	it('passes ordinary human mail', () => {
		expect(isAutoGenerated({ ...base, headers: {} })).toBe(false);
	});
});

describe('extractReplyText', () => {
	it('keeps everything when there is no quoted history', () => {
		expect(extractReplyText('Tuesday works for me!')).toBe('Tuesday works for me!');
	});

	it('cuts at "On … wrote:" and drops >-quoted lines', () => {
		const raw = [
			'Option 2 please.',
			'',
			'On Jul 1, 2026, at 9:12 AM, Cascade Plumbing <cascade@riv.us> wrote:',
			'> Here are the next openings:',
			'> 1. Tuesday…',
		].join('\n');
		expect(extractReplyText(raw)).toBe('Option 2 please.');
	});

	it('cuts at an "On … wrote:" attribution that a long address wrapped across lines', () => {
		const raw = [
			'Lets do Tuesday at 10AM',
			'',
			'On Fri, Jul 3, 2026 at 1:53 PM JW Riv Inc <jw-riv-inc-311ce5a1@dev.riv.us>',
			'wrote:',
			'',
			'> Here are a few openings:',
			'> 1. Tuesday 10:00 AM',
		].join('\n');
		expect(extractReplyText(raw)).toBe('Lets do Tuesday at 10AM');
	});

	it('cuts at Outlook-style From: blocks and dividers', () => {
		expect(extractReplyText('Yes!\nFrom: Rivus <a@riv.us>\nSent: things')).toBe('Yes!');
		expect(extractReplyText('Yes!\n________________________\nold stuff')).toBe('Yes!');
	});

	it('drops interleaved quote lines without a marker', () => {
		expect(extractReplyText('> old line\nMy reply\n> more old')).toBe('My reply');
	});

	it('keeps prose that merely opens with "On" and never closes an attribution', () => {
		const raw = ['On Tuesday I have a dentist appointment,', 'so Wednesday works better.'].join(
			'\n',
		);
		expect(extractReplyText(raw)).toBe(raw);
	});

	it('keeps multi-line prose whose lines happen to open with "On" and end with "wrote:"', () => {
		// No address or clock time, so this is prose the customer wrote, not a
		// quoted-history attribution — it must survive intact.
		const raw = ['On Tuesday I checked with Sam', 'and he wrote:', 'that Friday is best.'].join(
			'\n',
		);
		expect(extractReplyText(raw)).toBe(raw);
	});

	it('still strips a long single-line attribution beyond the old length budget', () => {
		const longName = `${'Cascade Plumbing & Heating of Springfield '.repeat(4)}LLC`;
		const attribution = `On Jul 1, 2026, at 9:12 AM, ${longName} <dispatch@cascade.example.com> wrote:`;
		expect(attribution.length).toBeGreaterThan(210);
		expect(extractReplyText(`Book it, thanks!\n\n${attribution}\n> old thread`)).toBe(
			'Book it, thanks!',
		);
	});
});

describe('htmlToText', () => {
	it('strips tags, decodes entities, and keeps block breaks', () => {
		expect(htmlToText('<div><p>Tuesday &amp; Thursday</p><p>work &lt;fine&gt;</p></div>')).toBe(
			'Tuesday & Thursday\nwork <fine>',
		);
	});

	it('drops style and script bodies', () => {
		expect(htmlToText('<style>p{color:red}</style><p>hello</p><script>x()</script>')).toBe('hello');
	});

	it('drops script bodies with lenient end tags (whitespace, newlines, junk before >)', () => {
		expect(htmlToText('<p>hello</p><script>x()</script >world')).toBe('hello\nworld');
		expect(htmlToText('<p>hi</p><script>evil()</script\t\n bar>there')).toBe('hi\nthere');
		expect(htmlToText('<script src="x">evil()</script>after')).toBe('after');
	});

	it('never double-unescapes entities', () => {
		// The author literally wrote "&lt;b&gt;" (encoded as &amp;lt;…) — it must
		// stay "&lt;b&gt;", not collapse twice into "<b>".
		expect(htmlToText('<p>&amp;lt;b&amp;gt;</p>')).toBe('&lt;b&gt;');
	});
});

describe('cleanSubject', () => {
	it('strips stacked Re:/Fwd: prefixes', () => {
		expect(cleanSubject('Re: RE: Fwd: Water heater')).toBe('Water heater');
		expect(cleanSubject('  FW:  Quote ')).toBe('Quote');
	});

	it('keeps a plain subject and empty stays empty', () => {
		expect(cleanSubject('Water heater')).toBe('Water heater');
		expect(cleanSubject('')).toBe('');
	});
});

describe('buildCustomerSignupUrl', () => {
	it('builds the join URL with the email prefilled', () => {
		expect(buildCustomerSignupUrl('https://www.rivus.ai/', 'cascade-plumbing', 'a+b@x.io')).toBe(
			'https://www.rivus.ai/customers/join/cascade-plumbing?email=a%2Bb%40x.io',
		);
	});
});

describe('agent email templates', () => {
	const context: AgentEmailRenderContext = {
		accountName: 'Cascade Plumbing',
		agentName: 'Rivus',
		customerName: 'Dana Fox',
		timeZone: 'America/Los_Angeles',
		signupUrl: 'https://www.rivus.ai/customers/join/cascade-plumbing?email=d%40x.io',
		jobTitle: 'Water heater install',
		inboundSubject: 'Re: Water heater',
		now: NOW,
	};
	const slots = [
		{ startAt: '2026-07-07T16:00:00.000Z', durationMinutes: 60 },
		{ startAt: '2026-07-09T21:00:00.000Z', durationMinutes: 60 },
	];

	it('threads the subject with Re: and falls back without one', () => {
		expect(replySubject('Re: Fwd: Water heater', 'Cascade Plumbing')).toBe('Re: Water heater');
		expect(replySubject('', 'Cascade Plumbing')).toBe('Scheduling with Cascade Plumbing');
	});

	it('renders offered slots as a numbered list in text and HTML', () => {
		const decision: AgentDecision = { kind: 'offer_slots', slots };
		const rendered = renderAgentEmail(decision, context);
		expect(rendered.subject).toBe('Re: Water heater');
		expect(rendered.text).toContain('Hi Dana,');
		expect(rendered.text).toContain('1. Tuesday, July 7 at 9:00 AM');
		expect(rendered.text).toContain('2. Thursday, July 9 at 2:00 PM');
		expect(rendered.text).toContain('Reply with the number');
		expect(rendered.html).toContain('Tuesday, July 7 at 9:00 AM');
		expect(rendered.html).toContain('Montserrat');
	});

	it('renders the signup invitation with the gradient button and link fallback', () => {
		const decision: AgentDecision = { kind: 'send_signup_link' };
		const rendered = renderAgentEmail(decision, { ...context, customerName: '' });
		expect(rendered.text).toContain('Hi there,');
		expect(rendered.text).toContain(context.signupUrl);
		expect(rendered.html).toContain('linear-gradient(135deg, #1ebefa, #6e1ec8)');
		expect(rendered.html).toContain('Join Cascade Plumbing as a customer');
	});

	it('renders a booking confirmation with the slot label and duration', () => {
		const decision: AgentDecision = {
			kind: 'book',
			slot: { startAt: '2026-07-07T16:00:00.000Z', durationMinutes: 60 },
		};
		const text = renderAgentReplyText(decision, context);
		expect(text).toContain("You're booked!");
		expect(text).toContain('Water heater install — Tuesday, July 7 at 9:00 AM (60 minutes).');
	});

	it('carries no sign-off after the body in the plain-text part', () => {
		const rendered = renderAgentEmail({ kind: 'offer_slots', slots }, context);
		expect(rendered.text).not.toContain('— Rivus, scheduling for');
		expect(rendered.text.trimEnd().endsWith('or suggest another time.')).toBe(true);
	});

	it('explains an unavailable time and lists alternatives', () => {
		const decision: AgentDecision = {
			kind: 'propose_unavailable',
			reason: 'taken',
			requestedStartAt: '2026-07-08T16:00:00.000Z',
			alternatives: slots,
		};
		const text = renderAgentReplyText(decision, context);
		expect(text).toContain('was just taken');
		expect(text).toContain('1. Tuesday, July 7 at 9:00 AM');
	});

	it('names the day an offer answers, and lists only that day', () => {
		const decision: AgentDecision = {
			kind: 'offer_slots',
			slots,
			// Midnight Pacific on Tuesday July 7th.
			requestedDayStartAt: '2026-07-07T07:00:00.000Z',
		};
		const text = renderAgentReplyText(decision, context);
		expect(text).toContain('has open on Tuesday, July 7:');
		expect(text).toContain('1. Tuesday, July 7 at 9:00 AM');
	});

	it('explains a day with nothing on it and offers the alternatives', () => {
		const decision: AgentDecision = {
			kind: 'day_unavailable',
			reason: 'closed',
			// Midnight Pacific on Saturday July 4th.
			requestedDayStartAt: '2026-07-04T07:00:00.000Z',
			alternatives: slots,
		};
		const text = renderAgentReplyText(decision, context);
		expect(text).toContain("we're closed on Saturday, July 4");
		expect(text).toContain('1. Tuesday, July 7 at 9:00 AM');
	});

	it('explains out-of-hours and in-the-past asks distinctly', () => {
		const outside: AgentDecision = {
			kind: 'propose_unavailable',
			reason: 'outside_hours',
			requestedStartAt: '2026-07-04T17:00:00.000Z',
			alternatives: [],
		};
		expect(renderAgentReplyText(outside, context)).toContain('outside our business hours');
		const past: AgentDecision = {
			kind: 'propose_unavailable',
			reason: 'in_past',
			requestedStartAt: '2026-06-01T16:00:00.000Z',
			alternatives: [],
		};
		expect(renderAgentReplyText(past, context)).toContain('already passed');
	});

	it('renders the fully-booked reply', () => {
		const text = renderAgentReplyText({ kind: 'no_availability' }, context);
		expect(text).toContain('fully booked');
	});

	it('escapes HTML in every interpolated value', () => {
		const rendered = renderAgentEmail(
			{ kind: 'offer_slots', slots },
			{ ...context, accountName: 'A<script>alert(1)</script>', customerName: '<b>x</b>' },
		);
		expect(rendered.html).not.toContain('<script>alert(1)</script>');
		expect(rendered.html).toContain('&lt;script&gt;');
	});
});

describe('ResendMailer.sendAgentEmail', () => {
	it('sends from the agent address with threading headers', async () => {
		const fetchImpl = vi.fn<FetchLike>().mockResolvedValue({
			ok: true,
			status: 200,
			text: async () => '{"id":"email_3"}',
		});
		const mailer = new ResendMailer({ apiKey: 're_k', from: 'Rivus <hello@rivus.ai>', fetchImpl });
		await mailer.sendAgentEmail({
			to: 'dana@example.com',
			from: 'Cascade Plumbing <cascade-plumbing@riv.us>',
			subject: 'Re: Water heater',
			html: '<p>hi</p>',
			text: 'hi',
			inReplyTo: '<abc@mail.example.com>',
			references: ['<abc@mail.example.com>'],
		});
		const [, init] = fetchImpl.mock.calls[0] as [string, { body: string }];
		const sent = JSON.parse(init.body);
		expect(sent.from).toBe('Cascade Plumbing <cascade-plumbing@riv.us>');
		expect(sent.headers).toEqual({
			'In-Reply-To': '<abc@mail.example.com>',
			References: '<abc@mail.example.com>',
		});
	});

	it('omits threading headers when starting a fresh thread', async () => {
		const fetchImpl = vi.fn<FetchLike>().mockResolvedValue({
			ok: true,
			status: 200,
			text: async () => '{}',
		});
		const mailer = new ResendMailer({ apiKey: 're_k', from: 'Rivus <hello@rivus.ai>', fetchImpl });
		await mailer.sendAgentEmail({
			to: 'dana@example.com',
			from: 'acme@riv.us',
			subject: 'Scheduling with Acme',
			html: '<p>hi</p>',
			text: 'hi',
			inReplyTo: '',
			references: [],
		});
		const [, init] = fetchImpl.mock.calls[0] as [string, { body: string }];
		expect(JSON.parse(init.body)).not.toHaveProperty('headers');
	});
});

describe('ResendReceivedEmailReader', () => {
	it('GETs the received email and maps its content', async () => {
		const fetchImpl = vi.fn<FetchLike>().mockResolvedValue({
			ok: true,
			status: 200,
			text: async () =>
				JSON.stringify({
					text: 'Tuesday works',
					html: '<p>Tuesday works</p>',
					headers: { 'auto-submitted': 'no' },
					message_id: '<abc@x>',
				}),
		});
		const reader = new ResendReceivedEmailReader({ apiKey: 're_k', fetchImpl });
		const content = await reader.get('email_1');
		expect(content).toEqual({
			text: 'Tuesday works',
			html: '<p>Tuesday works</p>',
			headers: { 'auto-submitted': 'no' },
			message_id: undefined,
			messageId: '<abc@x>',
		});
		const [url, init] = fetchImpl.mock.calls[0] as [
			string,
			{ method: string; headers: Record<string, string> },
		];
		expect(url).toBe('https://api.resend.com/emails/receiving/email_1');
		expect(init.method).toBe('GET');
		expect(init.headers.authorization).toBe('Bearer re_k');
	});

	it('tolerates null fields in the response', async () => {
		const fetchImpl = vi.fn<FetchLike>().mockResolvedValue({
			ok: true,
			status: 200,
			text: async () => JSON.stringify({ text: null, html: null, headers: null, message_id: null }),
		});
		const reader = new ResendReceivedEmailReader({ apiKey: 're_k', fetchImpl });
		expect(await reader.get('email_1')).toEqual({
			text: '',
			html: '',
			headers: {},
			messageId: '',
		});
	});

	it('returns null on HTTP errors, invalid JSON, and unexpected shapes', async () => {
		const error = vi
			.fn<FetchLike>()
			.mockResolvedValue({ ok: false, status: 404, text: async () => 'nope' });
		expect(await new ResendReceivedEmailReader({ apiKey: 'k', fetchImpl: error }).get('x')).toBe(
			null,
		);
		const badJson = vi
			.fn<FetchLike>()
			.mockResolvedValue({ ok: true, status: 200, text: async () => 'not json' });
		expect(await new ResendReceivedEmailReader({ apiKey: 'k', fetchImpl: badJson }).get('x')).toBe(
			null,
		);
		const badShape = vi
			.fn<FetchLike>()
			.mockResolvedValue({ ok: true, status: 200, text: async () => '{"text": 42}' });
		expect(await new ResendReceivedEmailReader({ apiKey: 'k', fetchImpl: badShape }).get('x')).toBe(
			null,
		);
	});
});

describe('createReceivedEmailReader', () => {
	it('is a no-op without an API key and real with one', () => {
		expect(createReceivedEmailReader({})).toBeInstanceOf(NoopReceivedEmailReader);
		expect(createReceivedEmailReader({ RESEND_API_KEY: 're_k' })).toBeInstanceOf(
			ResendReceivedEmailReader,
		);
	});

	it('NoopReceivedEmailReader always returns null', async () => {
		expect(await new NoopReceivedEmailReader().get('anything')).toBeNull();
	});
});
