import { type Account, type AccountId, stripAgentEmailTag } from '@rivus/core';
import type { FastifyBaseLogger, FastifyError, FastifyPluginAsync, FastifyRequest } from 'fastify';
import type { ZodTypeProvider } from 'fastify-type-provider-zod';
import { z } from 'zod';
import { errorResponseSchema } from '../http-schemas';
import { defaultCapabilities, type OrchestratorDeps } from '../services/agent/capabilities';
import type { InboundAgentMessage } from '../services/agent/channel';
import { createEmailChannelAdapter } from '../services/agent/email/adapter';
import {
	agentAddressLocalPart,
	EMAIL_BOUNCED_EVENT,
	EMAIL_COMPLAINED_EVENT,
	extractReplyText,
	htmlToText,
	INBOUND_EMAIL_EVENT,
	type InboundEmailEvent,
	inboundEmailEventSchema,
	isAutoGenerated,
	parseAddress,
	resolveAgentRecipient,
} from '../services/agent/email/inbound';
import { verifyWebhookSignature } from '../services/agent/email/webhook';
import { flagDeliveryFailure, handleInboundAgentMessage } from '../services/agent/orchestrator';

/**
 * The email channel of the scheduling agent: Resend posts every email received
 * at `*@AGENT_EMAIL_DOMAIN` here. This route owns only the email edges —
 * signature verification, the Resend event schema, resolving the account from the
 * recipient address, fetching the body, and the auto-responder loop guard — then
 * hands a normalized {@link InboundAgentMessage} to the channel-agnostic
 * {@link handleInboundAgentMessage}, which runs the same flow (and the same
 * capabilities) as every other channel.
 *
 * Everything unactionable answers `200 {handled:false}` rather than an error: the
 * sender is Resend, not the customer, and a non-2xx only makes it redeliver
 * something that will never become actionable.
 */

const webhookResponseSchema = z
	.object({
		/** Whether the agent acted on the email (replied/booked) or ignored it. */
		handled: z.boolean(),
		/** What the agent did (`offer_slots`, `book`, …) or why it ignored the email. */
		outcome: z.string(),
	})
	.meta({ id: 'AgentEmailWebhookResult' });

/** First value of a possibly-repeated header, as a string. */
function headerValue(value: string | string[] | undefined): string {
	if (Array.isArray(value)) {
		return value[0] ?? '';
	}
	return value ?? '';
}

export const agentEmailRoutes: FastifyPluginAsync = async (fastify) => {
	const app = fastify.withTypeProvider<ZodTypeProvider>();
	const {
		config,
		accounts,
		customers,
		conversations,
		agentThreads,
		memberships,
		mailer,
		notifier,
		receivedEmails,
	} = app.deps;

	const adapter = createEmailChannelAdapter({ config, customers, mailer });
	const capabilities = defaultCapabilities();
	// `AppDeps` is a structural superset of `OrchestratorDeps`, so the whole bag is
	// passed rather than hand-picked: what the core needs is the core's business, and
	// a capability that starts reading another repository must never be a route edit.
	const orchestratorDeps: OrchestratorDeps = app.deps;

	/**
	 * Resolve the account an agent-domain local part addresses. New addresses are
	 * `${slug}-${tag}`; older mail may carry the bare slug or the raw account id.
	 * Try the local part verbatim first, then peel the hex tag and resolve by slug.
	 */
	async function resolveAccountByLocalPart(localPart: string): Promise<Account | null> {
		const direct =
			(await accounts.findBySlug(localPart)) ?? (await accounts.findById(localPart as AccountId));
		if (direct) {
			return direct;
		}
		const slug = stripAgentEmailTag(localPart);
		return slug === localPart ? null : accounts.findBySlug(slug);
	}

	/**
	 * A reply Rivus sent bounced or was marked as spam: the customer never got it,
	 * so flag the thread's conversation for a human. The account is resolved from
	 * the delivery event's `From` (our own agent address), the contact from the
	 * failed recipient.
	 */
	async function handleDeliveryFailure(event: InboundEmailEvent, logger: FastifyBaseLogger) {
		const bounced = event.type === EMAIL_BOUNCED_EVENT;
		const sender = parseAddress(event.data.from);
		if (!sender) {
			return { handled: false, outcome: 'unparseable_sender' };
		}
		const localPart = agentAddressLocalPart(sender.address, config.AGENT_EMAIL_DOMAIN);
		if (!localPart) {
			return { handled: false, outcome: 'not_agent_sender' };
		}
		const account = await resolveAccountByLocalPart(localPart);
		if (!account || account.status === 'canceled') {
			return { handled: false, outcome: 'unknown_account' };
		}
		const recipient = parseAddress(event.data.to[0] ?? '');
		if (!recipient) {
			return { handled: false, outcome: 'unparseable_recipient' };
		}
		const noteBody = bounced
			? `Rivus's last email to ${recipient.address} bounced — they didn't receive it. Follow up another way.`
			: `${recipient.address} marked Rivus's last email as spam — reach out another way before emailing again.`;
		return flagDeliveryFailure({
			deps: { conversations, agentThreads, memberships, notifier },
			account,
			channel: 'email',
			contactAddress: recipient.address,
			noteBody,
			outcome: bounced ? 'delivery_bounced' : 'delivery_complained',
			logger,
		});
	}

	// Webhook signatures cover the exact bytes Resend sent, so this plugin scope
	// re-parses JSON from a string and keeps the raw payload for verification.
	const rawBodies = new WeakMap<FastifyRequest, string>();
	app.addContentTypeParser('application/json', { parseAs: 'string' }, (request, payload, done) => {
		rawBodies.set(request as FastifyRequest, payload as string);
		try {
			done(null, JSON.parse(payload as string));
		} catch {
			const error = new Error('Body is not valid JSON') as FastifyError;
			error.statusCode = 400;
			done(error, undefined);
		}
	});

	// Authenticity gate, before any parsing of the event itself. With a secret
	// configured every delivery must be signed; without one the route serves
	// unsigned payloads only outside production (local dev and tests).
	app.addHook('preValidation', async (request, reply) => {
		const secret = config.RESEND_WEBHOOK_SECRET;
		if (!secret) {
			if (config.NODE_ENV === 'production') {
				return reply.code(503).send({
					error: 'Service Unavailable',
					message: 'The email channel is not configured (RESEND_WEBHOOK_SECRET is unset).',
					statusCode: 503,
				});
			}
			return;
		}
		const verified = verifyWebhookSignature({
			secret,
			headers: {
				id: headerValue(request.headers['svix-id']),
				timestamp: headerValue(request.headers['svix-timestamp']),
				signature: headerValue(request.headers['svix-signature']),
			},
			payload: rawBodies.get(request) ?? '',
			now: new Date(),
		});
		if (!verified) {
			throw app.httpErrors.unauthorized('Invalid webhook signature');
		}
	});

	app.post(
		'/email/inbound',
		{
			schema: {
				tags: ['channels'],
				summary: 'Resend email webhook (inbound customer mail + delivery status)',
				description:
					'Resend delivers email events for the account’s agent address ' +
					'(`<account-slug>-<hex>@riv.us`) here. On `email.received` Rivus validates the ' +
					'sender against the account’s customers, keeps the multi-turn scheduling ' +
					'state on the thread, and replies by email — offering open times and ' +
					'booking the job once a time is agreed. On `email.bounced`/`email.complained` ' +
					'(a reply that never reached the customer) it flags the conversation for a ' +
					'human. Deliveries are authenticated with the Svix signature headers when ' +
					'`RESEND_WEBHOOK_SECRET` is configured.',
				body: z.unknown(),
				response: {
					200: webhookResponseSchema,
					401: errorResponseSchema,
					503: errorResponseSchema,
				},
			},
		},
		async (request) => {
			const parsed = inboundEmailEventSchema.safeParse(request.body);
			if (!parsed.success) {
				return { handled: false, outcome: 'unrecognized_payload' };
			}
			const event = parsed.data;
			// Outbound delivery failures: a reply Rivus sent never reached the customer.
			if (event.type === EMAIL_BOUNCED_EVENT || event.type === EMAIL_COMPLAINED_EVENT) {
				return handleDeliveryFailure(event, request.log);
			}
			if (event.type !== INBOUND_EMAIL_EVENT) {
				return { handled: false, outcome: 'ignored_event_type' };
			}

			// Which account was written to? The local part of the agent-domain recipient.
			const localPart = resolveAgentRecipient(event, config.AGENT_EMAIL_DOMAIN);
			if (!localPart) {
				return { handled: false, outcome: 'no_agent_recipient' };
			}
			const account = await resolveAccountByLocalPart(localPart);
			if (!account || account.status === 'canceled') {
				return { handled: false, outcome: 'unknown_account' };
			}

			const sender = parseAddress(event.data.from);
			if (!sender) {
				return { handled: false, outcome: 'unparseable_sender' };
			}

			// The webhook carries metadata only; pull the body/headers/Message-ID from
			// the received-emails API unless the payload embedded them.
			let text = event.data.text ?? '';
			let html = event.data.html ?? '';
			let headers = event.data.headers ?? {};
			let messageId = event.data.message_id;
			if (text === '' && html === '' && event.data.email_id !== '') {
				const fetched = await receivedEmails.get(event.data.email_id);
				if (!fetched) {
					// A 2xx here would permanently drop the customer's words (Resend never
					// redelivers an acknowledged event); a 5xx makes it retry later.
					throw app.httpErrors.internalServerError(
						'Could not fetch the inbound email body; the delivery will be retried.',
					);
				}
				text = fetched.text;
				html = fetched.html;
				headers = { ...fetched.headers, ...headers };
				messageId = messageId === '' ? fetched.messageId : messageId;
			}

			// Never answer machines: our own domain, out-of-office, delivery reports.
			if (
				isAutoGenerated({
					fromAddress: sender.address,
					agentDomain: config.AGENT_EMAIL_DOMAIN,
					headers,
				})
			) {
				return { handled: false, outcome: 'auto_generated' };
			}

			const rawText = text !== '' ? text : htmlToText(html);
			const message: InboundAgentMessage = {
				sender: { address: sender.address, name: sender.name },
				text: extractReplyText(rawText) || rawText.trim(),
				subject: event.data.subject,
				externalMessageId: messageId,
			};
			return handleInboundAgentMessage({
				deps: orchestratorDeps,
				adapter,
				capabilities,
				account,
				message,
				logger: request.log,
			});
		},
	);
};
